### ISSUE TITLE
[FEATURE]: Next.js starter

### ISSUE THREAD

**Issue by gfdias** [xgeekshq/divide-and-conquer#1]
## Summary

Create a [Next.js](https://nextjs.org/learn/basics/create-nextjs-app/setup) starter project

### Motivation

To kickstart D&C frontend development

**Comment by nuno-caseiro** [comment]
Hi guys, I intend to use this issue to associate with the first pull request that will be the next starter app. I would like to know what is your opinion about the best file structure that we should have in the repository. Should there be a frontend and backend folders with the respective projects?
